### ISSUE TITLE
[dglo on 2015-11-04 19:31:56] : pDAQ: Runs with hubs which fail to configure take a long time to fail

### ISSUE THREAD

**Issue by dglo** [dglo/juggler#139]
From run 127054:

CnCServer icecube.daq.juggler.component.StateTask-StateTask ERROR [2015-10-31 16:24:53.117] Configure failed
icecube.daq.juggler.component.DAQCompException: No Active DOMs on hub 61
        at icecube.daq.stringhub.StringHubComponent.configure(StringHubComponent.java:383)
        at icecube.daq.stringhub.StringHubComponent.configuring(StringHubComponent.java:359)
        at icecube.daq.juggler.component.StateTask.doConfigure(StateTask.java:147)
        at icecube.daq.juggler.component.StateTask.runInternal(StateTask.java:501)
        at icecube.daq.juggler.component.StateTask.run(StateTask.java:470)
        at java.lang.Thread.run(Thread.java:745)

CnCServer - - [2015-10-31 16:24:53.631140] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:24:55.387167] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:24:56.818849] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:24:58.257715] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:24:59.535884] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:00.906512] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:02.149729] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:03.506009] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:04.736591] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:06.103142] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:07.419063] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:09.027131] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:10.556614] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:11.783236] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:13.254146] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:14.465097] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:15.989378] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:17.199016] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:18.626098] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:19.905757] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:21.331882] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:22.632357] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:23.939786] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:25.243002] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:26.543782] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:27.834742] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:29.093196] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:30.362840] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:31.632705] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:32.930879] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:34.193533] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:35.464011] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:36.781013] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:38.073096] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:39.618852] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:40.989642] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:42.309876] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:43.572510] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:44.867369] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:46.142656] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:47.460466] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:48.732544] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:50.030053] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:51.223220] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:52.517057] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:53.695046] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:54.975075] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:56.270558] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:57.554914] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:25:58.872875] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:26:00.036631] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:26:01.241750] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:26:02.496934] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:26:03.771863] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:26:05.052557] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:26:06.315940] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:26:07.632489] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:26:08.946668] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:26:10.215095] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:26:11.396067] RunSet #3 (configuring): Waiting for configuring: stringHub#61
CnCServer - - [2015-10-31 16:26:12.697093] RunSet #3 (configuring): Waiting for configuring stringHub#61
CnCServer - - [2015-10-31 16:27:13.721747] Cycling components SecondaryBuilders, StringHub#1-86,201-211, eventBuilder, globalTrigger, iceTopTrigger, inIceTrigger

**Comment by dglo** [comment]
[dglo on 2015-11-04 19:33:54]
svn commit -m"Issue 7604: Fail quickly when there's an error in a component's state transition" dash/RunSet.py juggler/src/test/java/icecube/daq/juggler/component/DAQComponentTest.java juggler/src/main/java/icecube/daq/juggler/component/StateTask.java juggler/src/main/java/icecube/daq/juggler/component/DAQState.java
Sending        dash/RunSet.py
Sending        juggler/src/main/java/icecube/daq/juggler/component/DAQState.java
Sending        juggler/src/main/java/icecube/daq/juggler/component/StateTask.java
Sending        juggler/src/test/java/icecube/daq/juggler/component/DAQComponentTest.java
Transmitting file data ....
Committed revision 15857.

**Comment by dglo** [comment]
[dglo on 2016-03-22 16:05:59]
New_Glarus is almost here!
